"""empty message

Revision ID: 6de496563640
Revises: 
Create Date: 2022-02-23 17:16:19.303879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de496563640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_users_area_code', table_name='users')
    op.drop_index('ix_users_city', table_name='users')
    op.drop_index('ix_users_country', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_gender', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_index('ix_users_mobile_phone', table_name='users')
    op.drop_index('ix_users_profession', table_name='users')
    op.drop_index('ix_users_state', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=64), nullable=True),
    sa.Column('profession', sa.VARCHAR(length=64), nullable=True),
    sa.Column('area_code', sa.VARCHAR(length=6), nullable=True),
    sa.Column('mobile_phone', sa.BIGINT(), nullable=True),
    sa.Column('summary_text', sa.TEXT(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('state', sa.VARCHAR(length=64), nullable=True),
    sa.Column('country', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_state', 'users', ['state'], unique=False)
    op.create_index('ix_users_profession', 'users', ['profession'], unique=False)
    op.create_index('ix_users_mobile_phone', 'users', ['mobile_phone'], unique=False)
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_gender', 'users', ['gender'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_country', 'users', ['country'], unique=False)
    op.create_index('ix_users_city', 'users', ['city'], unique=False)
    op.create_index('ix_users_area_code', 'users', ['area_code'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('index', sa.VARCHAR(length=64), nullable=True),
    sa.Column('default', sa.BOOLEAN(), nullable=True),
    sa.Column('permissions', sa.INTEGER(), nullable=True),
    sa.Column('access_role', sa.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_role'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    # ### end Alembic commands ###
